@host = http://localhost:8789

GET {{host}}/users HTTP/1.1

###

POST {{host}}/users HTTP/1.1
content-type: application/json

{
    "firstName": "Tijana",
	"lastName": "Mladjenovic",
    "dateOfBirth": 52254732,
	"address": "Ceasdasd",
	"email": "ti111121a@example.org",
	"username": "ti21aggja1",
	"password": "tdasdasd1"
}

###
