@host = http://localhost:8789


# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "email" : "mladen@example.org",
	"password": "tdasdasd1"
}

###

GET {{host}}/api/users?page=2&size=5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
###

POST {{host}}/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "firstName": "Tijana",
	"lastName": "Mladjenovic",
    "dateOfBirth": 52254732,
	"address": "Ceasdasd",
	"email": "ti111121ppa@example.org",
	"username": "ti21appggja1",
	"password": "tdasdasd1"
}

###
